# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-05 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0002_goodie_main_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodie',
            name='main_image',
            field=models.FileField(default='settings.MEDIA_ROOT/placeholder500x500.png', upload_to='main_image/'),
        ),
    ]
